# Generated by Django 5.0.2 on 2024-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='manufactured_at',
            field=models.DateTimeField(default='2024-02-26 10:00:00', verbose_name='Дата производства продукта'),
        ),
    ]
