# Generated by Django 4.2 on 2024-04-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('edit_publication', 'изменить публикацию'), ('edit_description', 'изменить описание'), ('edit_categories', 'изменить категорию')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
